apiVersion: v1
kind: Service
metadata:
  name: api-{{TENANT_ID}}
  labels:
    app: api-{{TENANT_ID}}
spec:
  type: ClusterIP
  selector:
    app: api-{{TENANT_ID}}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP

